name: Continuous Delivery

on:
  release:
    types:
      - published

jobs:
  release:
    name: Binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true
          cache-dependency-path: go.sum

      - name: Get dependencies
        run: go mod download

      - name: Generate mock
        run: ./bin/mock.sh

      - name: Test
        run: go test ./...

      - name: Build
        run: make release

      - name: Upload
        run: |
          ./upload.sh ./bin/gtask-darwin-amd64 application/x-binary
          ./upload.sh ./bin/gtask-darwin-arm64 application/x-binary
          ./upload.sh ./bin/gtask-linux-amd64 application/x-binary
          ./upload.sh ./bin/gtask-linux-armv7 application/x-binary
          ./upload.sh ./bin/gtask-linux-arm64 application/x-binary
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
